apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-sakila
  labels:
    app.kubernetes.io/name: postgres-sakila
  namespace: postgres-sakila
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres-sakila
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres-sakila
    spec:
      containers:
      - name: postgres-sakila
        image: public.ecr.aws/m9h2b5e7/postgres-sakila:080124
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "sakila"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"